---
- name: installing apache httpd using copy module
  hosts: apphosts
  become: true
  vars:
    companyName: gp-world logistics
    lservice-gp: Check the GP logistics services
  tasks:
  - name: installing apache httpd using yum module
    yum:
     name: httpd
     state: latest
  - name: copying index file into host location
    template:
     src: index.html
     dest: /var/www/html/index.html
  - name: starting the httpd serivice
    service:
     name: httpd
     state: started
     enabled: true
 
...